version: '3.8'

services:
  app:
    build:
      target: builder
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    ports:
      - "27017:27017"
    command: ["mongod", "--logpath", "/dev/null"] 